const cfg=window.TRIKE_CONFIG, hasConfig=cfg&&!cfg.SUPABASE_URL.includes("YOUR-PROJECT")&&!cfg.SUPABASE_ANON_KEY.includes("YOUR_"), sb=hasConfig?window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY):null;
const $=id=>document.getElementById(id), money=n=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(n);
function show(e,on=true){e.classList.toggle("hidden",!on)} function toast(x){const t=$("toast");t.textContent=x;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),3000)}
const P={fuel:12500,eff:40,base:2500,service:.17,tax:.11,pools:{maintenance:.10,labor:.10,health:.10,old_age:.05,charity:.025,food:.075}};
function calc(trip,pick,cls){const fuelKm=P.fuel/P.eff,tripFuel=trip*fuelKm,pickFuel=pick*fuelKm,op=P.base+tripFuel+pickFuel,pool=Object.values(P.pools).reduce((a,b)=>a+b,0),driverPool=op*pool,service=(op+driverPool)*P.service,mult={standard:1,comfort:1.1,premium:1.2}[cls]||1,subtotal=(op+driverPool+service)*mult,tax=service*P.tax*mult,total=Math.ceil((subtotal+tax)/500)*500;return{total,tripFuel,pickFuel,driverPool,service:service*mult,tax,driverGross:total-service*mult-tax}}
async function profile(){const {data:{session}}=await sb.auth.getSession();if(!session)return null;const {data}=await sb.from("profiles").select("*").eq("id",session.user.id).single();return data}
async function refresh(){if(!sb){show($("authView"),true);$("authMsg").textContent="Supabase belum dikonfigurasi. Edit js/config.js.";return}const p=await profile();if(!p){show($("authView"),true);return}show($("authView"),false);show($("appView"),true);show($("logoutBtn"),true);$("userName").textContent=p.full_name;$("roleBadge").textContent=p.role==="driver"?"DRIVER":"PENUMPANG";$("verificationBadge").innerHTML=p.identity_verified?'<span class="badge verified">IDENTITAS TERVERIFIKASI</span>':'<span class="badge">IDENTITAS BELUM TERVERIFIKASI</span>';show($("passengerView"),p.role==="passenger");show($("driverView"),p.role==="driver");p.role==="passenger"?loadPassenger():loadDriver()}
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");show($("loginForm"),b.dataset.tab==="login");show($("registerForm"),b.dataset.tab==="register");$("authMsg").textContent=""});
$("registerForm").onsubmit=async e=>{e.preventDefault();if(!sb)return;const name=$("regName").value,email=$("regEmail").value,password=$("regPassword").value,role=$("regRole").value;const {data,error}=await sb.auth.signUp({email,password,options:{data:{full_name:name,role}}});if(error){$("authMsg").textContent=error.message;return}$("authMsg").textContent=data.session?"Akun dibuat.":"Akun dibuat, silakan konfirmasi email jika diminta."};
$("loginForm").onsubmit=async e=>{e.preventDefault();if(!sb)return;const{error}=await sb.auth.signInWithPassword({email:$("loginEmail").value,password:$("loginPassword").value});if(error)$("authMsg").textContent=error.message;else refresh()};$("logoutBtn").onclick=async()=>{await sb.auth.signOut();location.reload()};
$("quoteBtn").onclick=()=>{const q=calc(+$("tripKm").value,+$("pickupKm").value,$("serviceClass").value);$("quoteBox").innerHTML=`<div>Estimasi tarif</div><div class="price">${money(q.total)}</div><small>BBM perjalanan ${money(q.tripFuel)} · BBM jemput ${money(q.pickFuel)} · Driver pool ${money(q.driverPool)} · Layanan ${money(q.service)} · Pajak ${money(q.tax)}</small>`;show($("quoteBox"));show($("requestBtn"));$("requestBtn").dataset.q=JSON.stringify(q)};
$("requestBtn").onclick=async()=>{const p=await profile(),q=JSON.parse($("requestBtn").dataset.q);const{error}=await sb.from("rides").insert({passenger_id:p.id,pickup_text:$("pickupText").value||"Lokasi penjemputan",pickup_distance_km:+$("pickupKm").value,trip_distance_km:+$("tripKm").value,service_class:$("serviceClass").value,estimated_fare:q.total,status:"requested"});if(error)toast(error.message);else{toast("Order dibuat.");loadPassenger()}};
async function loadPassenger(){const p=await profile(),{data}=await sb.from("rides").select("*").eq("passenger_id",p.id).order("created_at",{ascending:false}).limit(10);$("ordersPassenger").innerHTML=data?.length?data.map(r=>`<div class=item><div class=row><b>${r.pickup_text}</b><span class=badge>${r.status}</span></div><small>${r.trip_distance_km} km · ${money(r.estimated_fare||0)}</small></div>`).join(""):"<div class=item>Belum ada pesanan.</div>"}
async function loadDriver(){const p=await profile(),{data:d}=await sb.from("drivers").select("*").eq("id",p.id).maybeSingle();$("onlineStatus").textContent=d?.is_online?"ONLINE":"OFFLINE";$("onlineStatus").className="badge "+(d?.is_online?"verified":"");$("toggleOnline").textContent=d?.is_online?"Offline":"Online";$("driverWallet").textContent=money(d?.wallet_balance||0);const{data:r}=await sb.from("rides").select("*").eq("status","requested").order("created_at").limit(10);$("driverOrders").innerHTML=r?.length?r.map(x=>`<div class=item><div class=row><b>${x.pickup_text}</b><button class=primary onclick="acceptRide('${x.id}')">Ambil</button></div><small>Jemput ${x.pickup_distance_km} km · Trip ${x.trip_distance_km} km · ${money(x.estimated_fare)}</small></div>`).join(""):"<div class=item>Tidak ada order.</div>"}
$("toggleOnline").onclick=async()=>{const p=await profile(),{data:d}=await sb.from("drivers").select("is_online").eq("id",p.id).single();await sb.from("drivers").update({is_online:!d.is_online}).eq("id",p.id);loadDriver()};window.acceptRide=async id=>{const p=await profile(),{error}=await sb.from("rides").update({driver_id:p.id,status:"accepted",accepted_at:new Date().toISOString()}).eq("id",id).eq("status","requested");if(error)toast(error.message);else{toast("Order diterima.");loadDriver()}};if(sb)sb.auth.onAuthStateChange(()=>setTimeout(refresh,0));refresh();